# f=open('student.txt','w')
# f.write('hello')
# f.write('geekyshows')
# f.write('how are you')
# f.close()


# f=open('student.txt','w')
# f.write('hello\n')
# f.write('geekyshows\n')
# f.write('how are you')
# f.close()

# f=open('student.txt','w')
# n=f.write('hello')
# a=f.write('geekyshows')
# b=f.write('how are you')
# print(n)
# print(a)
# print(b)
# f.close()

f=open('student.txt','a')
f.write(' hello')
f.close()